spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      retry:
        max-attempts: 5