spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
    fail-fast: true
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      retry:
        max-attempts: 5

