spring.application.name=product-service
server.port= 8181

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce_db?characterEncoding=latin1&useConfigs=maxPerformance&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=''
spring.datasource.username = root
spring.datasource.password = Subham@1234
spring.jpa.hibernate.ddl-auto=update